const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="samsamsun789@gmail.com"
global.location="Lahore,Pakistan."
global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"
global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/d5b1c3544fedc23e11a06.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "919539209049" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "919539209049";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "true"; 
global.wlcm  = process.env.WELCOME || "true";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "set according to your need" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "923184474176,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "true"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://suhail-md-vtsf.onrender.com/";

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.8",
  caption : process.env.CAPTION || "©sᴜʜᴀɪʟ²²¹-ᴍᴅ" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "Sulthaan",
  packname: process.env.PACK_NAME || "♥️",
  botname : process.env.BOT_NAME  || "sᴜʜᴀɪʟ-ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "It'x Sulthaan",

  sessionName:process.env.SESSION_ID || "SUHAIL_22_19_09_26_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTY4LFxuICAgICAgICA2OCxcbiAgICAgICAgMjAxLFxuICAgICAgICAyMDMsXG4gICAgICAgIDE4NixcbiAgICAgICAgNDgsXG4gICAgICAgIDExNSxcbiAgICAgICAgNzMsXG4gICAgICAgIDI5LFxuICAgICAgICA5MixcbiAgICAgICAgMjMsXG4gICAgICAgIDMwLFxuICAgICAgICAxODMsXG4gICAgICAgIDE1MyxcbiAgICAgICAgNTUsXG4gICAgICAgIDY3LFxuICAgICAgICAwLFxuICAgICAgICAyOSxcbiAgICAgICAgOTgsXG4gICAgICAgIDEyNSxcbiAgICAgICAgOTQsXG4gICAgICAgIDQsXG4gICAgICAgIDQ0LFxuICAgICAgICAyNTMsXG4gICAgICAgIDksXG4gICAgICAgIDI0MixcbiAgICAgICAgMTIwLFxuICAgICAgICAxMzIsXG4gICAgICAgIDU1LFxuICAgICAgICAxMDMsXG4gICAgICAgIDEsXG4gICAgICAgIDc2XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDE3MSxcbiAgICAgICAgMTU3LFxuICAgICAgICAxNzgsXG4gICAgICAgIDE0MSxcbiAgICAgICAgNjcsXG4gICAgICAgIDIyNixcbiAgICAgICAgMjEyLFxuICAgICAgICAxNCxcbiAgICAgICAgNjksXG4gICAgICAgIDE5NSxcbiAgICAgICAgMjE3LFxuICAgICAgICAyMTAsXG4gICAgICAgIDc1LFxuICAgICAgICA2NixcbiAgICAgICAgOTIsXG4gICAgICAgIDIxLFxuICAgICAgICA4OCxcbiAgICAgICAgNSxcbiAgICAgICAgMjQ3LFxuICAgICAgICA0MixcbiAgICAgICAgNTksXG4gICAgICAgIDAsXG4gICAgICAgIDE5LFxuICAgICAgICA3MixcbiAgICAgICAgNzEsXG4gICAgICAgIDE2LFxuICAgICAgICAyMDksXG4gICAgICAgIDEwMyxcbiAgICAgICAgMjA5LFxuICAgICAgICAxODksXG4gICAgICAgIDE1MSxcbiAgICAgICAgOTJcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwicGFpcmluZ0VwaGVtZXJhbEtleVBhaXJcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDMyLFxuICAgICAgICA2MyxcbiAgICAgICAgNjYsXG4gICAgICAgIDYzLFxuICAgICAgICAxMTQsXG4gICAgICAgIDg5LFxuICAgICAgICAxNzcsXG4gICAgICAgIDE1NyxcbiAgICAgICAgMTMsXG4gICAgICAgIDg0LFxuICAgICAgICAyMTEsXG4gICAgICAgIDIwNyxcbiAgICAgICAgMjUzLFxuICAgICAgICAxMDIsXG4gICAgICAgIDM0LFxuICAgICAgICA3MCxcbiAgICAgICAgMTY5LFxuICAgICAgICAyNDUsXG4gICAgICAgIDE3MixcbiAgICAgICAgMTAwLFxuICAgICAgICA5NyxcbiAgICAgICAgMzcsXG4gICAgICAgIDEzNCxcbiAgICAgICAgMzEsXG4gICAgICAgIDE5MyxcbiAgICAgICAgOTksXG4gICAgICAgIDE5OCxcbiAgICAgICAgNzAsXG4gICAgICAgIDE0NSxcbiAgICAgICAgMTU3LFxuICAgICAgICAxMDIsXG4gICAgICAgIDEyNlxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA2NSxcbiAgICAgICAgMTcyLFxuICAgICAgICAxMzMsXG4gICAgICAgIDEyNCxcbiAgICAgICAgMjIwLFxuICAgICAgICAyMDUsXG4gICAgICAgIDM2LFxuICAgICAgICAxNzYsXG4gICAgICAgIDIwMyxcbiAgICAgICAgNTIsXG4gICAgICAgIDIzMSxcbiAgICAgICAgMTczLFxuICAgICAgICAxODUsXG4gICAgICAgIDE3NyxcbiAgICAgICAgMTA2LFxuICAgICAgICA0MyxcbiAgICAgICAgMTUxLFxuICAgICAgICAyMjgsXG4gICAgICAgIDEwNixcbiAgICAgICAgMTkzLFxuICAgICAgICAxMTcsXG4gICAgICAgIDEzMixcbiAgICAgICAgMTI4LFxuICAgICAgICAxODgsXG4gICAgICAgIDk0LFxuICAgICAgICA5LFxuICAgICAgICAyMTksXG4gICAgICAgIDEwLFxuICAgICAgICAyMDYsXG4gICAgICAgIDkyLFxuICAgICAgICAxNzIsXG4gICAgICAgIDE1XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZElkZW50aXR5S2V5XCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAwLFxuICAgICAgICAxMTcsXG4gICAgICAgIDc4LFxuICAgICAgICAxMTYsXG4gICAgICAgIDgzLFxuICAgICAgICAxMjIsXG4gICAgICAgIDIxNCxcbiAgICAgICAgOTcsXG4gICAgICAgIDgwLFxuICAgICAgICAxOTIsXG4gICAgICAgIDY5LFxuICAgICAgICA2OSxcbiAgICAgICAgMjAxLFxuICAgICAgICAyOCxcbiAgICAgICAgMTcxLFxuICAgICAgICAxNTgsXG4gICAgICAgIDE3OCxcbiAgICAgICAgMTUxLFxuICAgICAgICAxNDcsXG4gICAgICAgIDE3MyxcbiAgICAgICAgMCxcbiAgICAgICAgMjM2LFxuICAgICAgICAzOCxcbiAgICAgICAgMjQsXG4gICAgICAgIDI1NCxcbiAgICAgICAgMjEyLFxuICAgICAgICAyMTgsXG4gICAgICAgIDE3OCxcbiAgICAgICAgMjA3LFxuICAgICAgICA3MCxcbiAgICAgICAgMTQ1LFxuICAgICAgICA2OFxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA4NixcbiAgICAgICAgMTUxLFxuICAgICAgICAyNTIsXG4gICAgICAgIDI1MSxcbiAgICAgICAgMTgxLFxuICAgICAgICAyMDEsXG4gICAgICAgIDEzLFxuICAgICAgICAyOSxcbiAgICAgICAgODEsXG4gICAgICAgIDI0MixcbiAgICAgICAgMjUzLFxuICAgICAgICA2NCxcbiAgICAgICAgMTU1LFxuICAgICAgICAxNjUsXG4gICAgICAgIDEzOSxcbiAgICAgICAgMTIyLFxuICAgICAgICA3MCxcbiAgICAgICAgODQsXG4gICAgICAgIDE1NSxcbiAgICAgICAgNyxcbiAgICAgICAgNSxcbiAgICAgICAgNDgsXG4gICAgICAgIDE5MixcbiAgICAgICAgNTAsXG4gICAgICAgIDEwOSxcbiAgICAgICAgMjAzLFxuICAgICAgICA1MSxcbiAgICAgICAgMTIsXG4gICAgICAgIDE3NixcbiAgICAgICAgMTQsXG4gICAgICAgIDI0MixcbiAgICAgICAgMTA2XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZFByZUtleVwiOiB7XG4gICAgXCJrZXlQYWlyXCI6IHtcbiAgICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDgwLFxuICAgICAgICAgIDE5NCxcbiAgICAgICAgICAxMTgsXG4gICAgICAgICAgMzIsXG4gICAgICAgICAgMTI0LFxuICAgICAgICAgIDE3LFxuICAgICAgICAgIDExNyxcbiAgICAgICAgICAxNDIsXG4gICAgICAgICAgNDAsXG4gICAgICAgICAgNzksXG4gICAgICAgICAgNTIsXG4gICAgICAgICAgMjUsXG4gICAgICAgICAgMjQsXG4gICAgICAgICAgMTIsXG4gICAgICAgICAgMjE2LFxuICAgICAgICAgIDEyOCxcbiAgICAgICAgICAxMDAsXG4gICAgICAgICAgMjI1LFxuICAgICAgICAgIDE5NCxcbiAgICAgICAgICAxMTcsXG4gICAgICAgICAgMjI2LFxuICAgICAgICAgIDIzOSxcbiAgICAgICAgICA2NixcbiAgICAgICAgICAzNixcbiAgICAgICAgICAxNjcsXG4gICAgICAgICAgMTAzLFxuICAgICAgICAgIDcwLFxuICAgICAgICAgIDM1LFxuICAgICAgICAgIDk1LFxuICAgICAgICAgIDEzNixcbiAgICAgICAgICAxMDgsXG4gICAgICAgICAgMTEwXG4gICAgICAgIF1cbiAgICAgIH0sXG4gICAgICBcInB1YmxpY1wiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDI3LFxuICAgICAgICAgIDI0MSxcbiAgICAgICAgICAyMSxcbiAgICAgICAgICA4NSxcbiAgICAgICAgICAzNyxcbiAgICAgICAgICAyMzIsXG4gICAgICAgICAgMjQyLFxuICAgICAgICAgIDUyLFxuICAgICAgICAgIDIyMCxcbiAgICAgICAgICAxNTYsXG4gICAgICAgICAgMzYsXG4gICAgICAgICAgNDUsXG4gICAgICAgICAgMTYsXG4gICAgICAgICAgMTgsXG4gICAgICAgICAgMjcsXG4gICAgICAgICAgNjYsXG4gICAgICAgICAgMjQyLFxuICAgICAgICAgIDIyNSxcbiAgICAgICAgICAyMjEsXG4gICAgICAgICAgMjM1LFxuICAgICAgICAgIDg1LFxuICAgICAgICAgIDI0LFxuICAgICAgICAgIDc4LFxuICAgICAgICAgIDE3MixcbiAgICAgICAgICAxMDgsXG4gICAgICAgICAgMTk4LFxuICAgICAgICAgIDI0NSxcbiAgICAgICAgICAyMyxcbiAgICAgICAgICAyMSxcbiAgICAgICAgICAzMixcbiAgICAgICAgICAxNDcsXG4gICAgICAgICAgMTE4XG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9LFxuICAgIFwic2lnbmF0dXJlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgNTYsXG4gICAgICAgIDIwNCxcbiAgICAgICAgMTI1LFxuICAgICAgICA4OSxcbiAgICAgICAgMzgsXG4gICAgICAgIDI1MyxcbiAgICAgICAgNDQsXG4gICAgICAgIDM1LFxuICAgICAgICAxMDAsXG4gICAgICAgIDI0NyxcbiAgICAgICAgMTAxLFxuICAgICAgICAzMyxcbiAgICAgICAgMTc2LFxuICAgICAgICAyMzksXG4gICAgICAgIDEwNyxcbiAgICAgICAgMjIzLFxuICAgICAgICAyMDIsXG4gICAgICAgIDY5LFxuICAgICAgICAyMzMsXG4gICAgICAgIDEzNyxcbiAgICAgICAgNzIsXG4gICAgICAgIDEzOCxcbiAgICAgICAgMTA0LFxuICAgICAgICA5NixcbiAgICAgICAgNDMsXG4gICAgICAgIDI0NyxcbiAgICAgICAgMTgxLFxuICAgICAgICA3MSxcbiAgICAgICAgMTQ4LFxuICAgICAgICAxNDgsXG4gICAgICAgIDIzOSxcbiAgICAgICAgMjE5LFxuICAgICAgICAyMjksXG4gICAgICAgIDE2OCxcbiAgICAgICAgMjU0LFxuICAgICAgICAxOTcsXG4gICAgICAgIDEzMixcbiAgICAgICAgMTE5LFxuICAgICAgICA4MyxcbiAgICAgICAgMTE4LFxuICAgICAgICAxMyxcbiAgICAgICAgMTQ5LFxuICAgICAgICAyMjgsXG4gICAgICAgIDkyLFxuICAgICAgICAxNzgsXG4gICAgICAgIDI4LFxuICAgICAgICAxNjEsXG4gICAgICAgIDc1LFxuICAgICAgICAyMDQsXG4gICAgICAgIDEyNSxcbiAgICAgICAgOTQsXG4gICAgICAgIDE1NixcbiAgICAgICAgMTgsXG4gICAgICAgIDQyLFxuICAgICAgICA5OCxcbiAgICAgICAgMjQsXG4gICAgICAgIDc0LFxuICAgICAgICAyMjMsXG4gICAgICAgIDIsXG4gICAgICAgIDIyLFxuICAgICAgICAxNzIsXG4gICAgICAgIDE3NyxcbiAgICAgICAgMjA2LFxuICAgICAgICAxMzBcbiAgICAgIF1cbiAgICB9LFxuICAgIFwia2V5SWRcIjogMVxuICB9LFxuICBcInJlZ2lzdHJhdGlvbklkXCI6IDE5MSxcbiAgXCJhZHZTZWNyZXRLZXlcIjogXCJ5V0xma1QxVDM2UHBRK3RFK01udU5CZUhlVmJYT1lyQ21LSlJjY0R2QWpjPVwiLFxuICBcInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlc1wiOiBbXG4gICAge1xuICAgICAgXCJrZXlcIjoge1xuICAgICAgICBcInJlbW90ZUppZFwiOiBcIjkxOTUzOTIwOTA0OUBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImZyb21NZVwiOiB0cnVlLFxuICAgICAgICBcImlkXCI6IFwiODVFMjg4ODU5QTNGRjM4MEUzMENEMjgxNzdENzMzRkRcIlxuICAgICAgfSxcbiAgICAgIFwibWVzc2FnZVRpbWVzdGFtcFwiOiAxNzI3Mzg5MTc4XG4gICAgfSxcbiAgICB7XG4gICAgICBcImtleVwiOiB7XG4gICAgICAgIFwicmVtb3RlSmlkXCI6IFwiOTE5NTM5MjA5MDQ5QHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZnJvbU1lXCI6IHRydWUsXG4gICAgICAgIFwiaWRcIjogXCIyOUEwQ0YwNjBEODQxQjM5NzVDNjRDMDU5Q0E0MThGMlwiXG4gICAgICB9LFxuICAgICAgXCJtZXNzYWdlVGltZXN0YW1wXCI6IDE3MjczODkxNzlcbiAgICB9XG4gIF0sXG4gIFwibmV4dFByZUtleUlkXCI6IDMxLFxuICBcImZpcnN0VW51cGxvYWRlZFByZUtleUlkXCI6IDMxLFxuICBcImFjY291bnRTeW5jQ291bnRlclwiOiAxLFxuICBcImFjY291bnRTZXR0aW5nc1wiOiB7XG4gICAgXCJ1bmFyY2hpdmVDaGF0c1wiOiBmYWxzZVxuICB9LFxuICBcImRldmljZUlkXCI6IFwiWjFzcnBYTlNRbWlReGpVdGl1eUIwd1wiLFxuICBcInBob25lSWRcIjogXCJlM2I0ODAyZC1lZGUwLTQ2YjctODU5My1kNThlMWViM2Q0MzJcIixcbiAgXCJpZGVudGl0eUlkXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMzcsXG4gICAgICAyNTEsXG4gICAgICA5NSxcbiAgICAgIDc5LFxuICAgICAgMTQ3LFxuICAgICAgMTc0LFxuICAgICAgNzUsXG4gICAgICAxNjAsXG4gICAgICA1MCxcbiAgICAgIDcsXG4gICAgICAyNDUsXG4gICAgICA1NyxcbiAgICAgIDYyLFxuICAgICAgMjMsXG4gICAgICA3MSxcbiAgICAgIDcxLFxuICAgICAgOTEsXG4gICAgICAxODksXG4gICAgICAyMzQsXG4gICAgICAxODBcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0ZXJlZFwiOiB0cnVlLFxuICBcImJhY2t1cFRva2VuXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgNDUsXG4gICAgICAyMDAsXG4gICAgICAxODgsXG4gICAgICAxMyxcbiAgICAgIDk3LFxuICAgICAgMjMzLFxuICAgICAgMjEyLFxuICAgICAgMTAxLFxuICAgICAgMjM5LFxuICAgICAgMTA3LFxuICAgICAgMTQ5LFxuICAgICAgOTIsXG4gICAgICAxNDYsXG4gICAgICAxNjEsXG4gICAgICAzOCxcbiAgICAgIDg5LFxuICAgICAgNDMsXG4gICAgICAyMTQsXG4gICAgICAxOTEsXG4gICAgICAxOTZcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uXCI6IHt9LFxuICBcInBhaXJpbmdDb2RlXCI6IFwiUEo5OUNOQjFcIixcbiAgXCJtZVwiOiB7XG4gICAgXCJpZFwiOiBcIjkxOTUzOTIwOTA0OTo1QHMud2hhdHNhcHAubmV0XCIsXG4gICAgXCJsaWRcIjogXCIxODYyNzMxMTc1NTY4MDY6NUBsaWRcIixcbiAgICBcIm5hbWVcIjogXCLDg86yzrLDg8WcxpHDg8WYxZzhurjhurjFh8ODXCJcbiAgfSxcbiAgXCJhY2NvdW50XCI6IHtcbiAgICBcImRldGFpbHNcIjogXCJDTC9lejl3RkVQSzcxN2NHR0FFZ0FDZ0FcIixcbiAgICBcImFjY291bnRTaWduYXR1cmVLZXlcIjogXCJXK2ZFRFk1bVFZMUlLZWc4dWp4U2tjanhWelpVYVRUM1o0K285bDhlemtJPVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZVwiOiBcIk55ekM1MUFLOWxQRFViVVh4eVNtSndZL1dOTTk5eUdKL09oM0xjdDFwNkJDMUw1ZUFBWVE4b3dZK2RaV3Z0eUNjTHIvQ3hvUmw2MWVHdCtFSitPTEJnPT1cIixcbiAgICBcImRldmljZVNpZ25hdHVyZVwiOiBcIks4S3lScWN5Z2xuZEhwWk1FdmpBZzhEYnQzQmtrSUNlcWNmV0hUcGxuWkx3TVMzVnRVTE9uWTdUTzlCME9XZDM1ZGdjL0RHZnpJaFp1cHJVaFlnQWl3PT1cIlxuICB9LFxuICBcInNpZ25hbElkZW50aXRpZXNcIjogW1xuICAgIHtcbiAgICAgIFwiaWRlbnRpZmllclwiOiB7XG4gICAgICAgIFwibmFtZVwiOiBcIjkxOTUzOTIwOTA0OTo1QHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZGV2aWNlSWRcIjogMFxuICAgICAgfSxcbiAgICAgIFwiaWRlbnRpZmllcktleVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDUsXG4gICAgICAgICAgOTEsXG4gICAgICAgICAgMjMxLFxuICAgICAgICAgIDE5NixcbiAgICAgICAgICAxMyxcbiAgICAgICAgICAxNDIsXG4gICAgICAgICAgMTAyLFxuICAgICAgICAgIDY1LFxuICAgICAgICAgIDE0MSxcbiAgICAgICAgICA3MixcbiAgICAgICAgICA0MSxcbiAgICAgICAgICAyMzIsXG4gICAgICAgICAgNjAsXG4gICAgICAgICAgMTg2LFxuICAgICAgICAgIDYwLFxuICAgICAgICAgIDgyLFxuICAgICAgICAgIDE0NSxcbiAgICAgICAgICAyMDAsXG4gICAgICAgICAgMjQxLFxuICAgICAgICAgIDg3LFxuICAgICAgICAgIDU0LFxuICAgICAgICAgIDg0LFxuICAgICAgICAgIDEwNSxcbiAgICAgICAgICA1MixcbiAgICAgICAgICAyNDcsXG4gICAgICAgICAgMTAzLFxuICAgICAgICAgIDE0MyxcbiAgICAgICAgICAxNjgsXG4gICAgICAgICAgMjQ2LFxuICAgICAgICAgIDk1LFxuICAgICAgICAgIDMwLFxuICAgICAgICAgIDIwNixcbiAgICAgICAgICA2NlxuICAgICAgICBdXG4gICAgICB9XG4gICAgfVxuICBdLFxuICBcInBsYXRmb3JtXCI6IFwiYW5kcm9pZFwiLFxuICBcImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcFwiOiAxNzI3Mzg5MTc0LFxuICBcIm15QXBwU3RhdGVLZXlJZFwiOiBcIkFBQUFBRTNKXCJcbn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFFM0ouanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJYOXdFeXRPMERvclc4a0d0MFl5ZVd6ZnZLTEtlMDVxZkdONmpycXB1R1pvPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjE1MzY0MjE2OTQsXCJjdXJyZW50SW5kZXhcIjoxLFwiZGV2aWNlSW5kZXhlc1wiOlswLDFdfSxcInRpbWVzdGFtcFwiOlwiMFwifSIKfQ==",  // PUT SESSION ID HERE 
  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "public",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "SUHAIL",



};




























global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
